### ISSUE TITLE
FR13. Add budget view (name, cost, date)

### ISSUE THREAD

**Issue by Ahmed-Alagbari** [WSU-4110/budgie#13]
|  FR13. Add budget view (name, cost, date)  |
|-----------------------|
| Goal: FR13 allows the user to create budget categories |
| Stakeholders: All Users |
|Description: After selecting the “Add budget view” button, a page that allows the user to add a new budget will pop up. This page will let the user name a new budget category, along with a setting to set the budget value.  |
| Origin: Team meeting on 1/31 |
| Version: 1.0 | 
| Date: 01/31/2023 |
| Priority: 2 |

**Comment by JayanthAnandNama** [comment]
The button is completed, however, the form is not done on the second page.
