### ISSUE TITLE
FR3. Show total budget status

### ISSUE THREAD

**Issue by Ahmed-Alagbari** [WSU-4110/budgie#3]
|  FR3. Show total budget status |
|-----------------------|
| Goal: FR3 will allow the user to see the status of all budgets in total |
| Stakeholders: All Users |
| Description: On the homepage users will see a circular progress bar that shows the total amount of all budgets and the amount spent from those budgets. The progress bar starts full and decreases with each transaction entered. |
| Origin: Team meeting on 1/31 |
| Version: 1.0 | 
| Date: 01/31/2023 |
| Priority: 1 |

**Comment by Rey-Jey** [comment]
We'll have to modify the variables later for a more organized backend, but as of right now the code works

**Comment by amuwhao46** [comment]
The circle and the horizontal progress bar (Breakdown category) will decrease as the user accomplishes the budget
